### ISSUE TITLE
does not produce correct PPM signal

### ISSUE THREAD

**Issue by RomanLut** [ps-after-hours/esp32_ppm_output#2]
Code does not produce correct PPM signal due to commented line:

 // ppmOutput = LOW;

Expected format: https://sourceforge.net/p/arduinorclib/wiki/PPM%20Signal/

**Comment by DzikuVx** [comment]
PPM can be either normal LOW or normal HIGH. Proper decoder should understand both dialected

**Comment by RomanLut** [comment]
In PPM description above each channel starts from 500us pulse.
Such signal is generated by code:
https://quadmeup.com/how-to-generate-ppm-signal-with-esp32-and-arduino/

The code in this repository generates alternating pulses with duration of channel.
I guess this is some different PPM dialect.
It is accepted by inav though.
Just placing comment here so other people can understand.
